### PR TITLE
backend:  fix multichoice json, new question types, accesstest - clean up previous testfiles

### PR DESCRIPTION
**Pull request by RoboSparrow**
- #74 fix `fcgimain.c` issue with rendering empty json options (per comma), also fixes tests 
- #85 add `survey.h` define some new question types 
- #84 fix `fcgimain.c`  accesstest: remove existing test flies
- #93 fix missing `description` header in test files
- add some backend dirs and files

### CODE REVIEW

**Comment by RoboSparrow** [comment]
```bash
head -n1 -q backend/tests/*.test
description Python implementation of nextquestion can be used
description Python implementation of nextquestion can be used
description Python implementation of nextquestion can be used
description Answer questions, and obtain a sensible next question each time
description Answer questions, and obtain a sensible next question each time
description test infrastructure shuold check syntax in test file (in this case, defined survey has wrong name)
description test infrastructure shuold check syntax in test file (in this case, endOfSurvey line is missing) 
test infrastructure shuold check syntax in test file (in this case, defined survey has wrong name)
test infrastructure shuold check syntax in test file (in this case, endOfSurvey line is missing) 
description FastCGI binary can access required paths
description Answer a question in a survey
description Answer a question in a survey
description Create a new session
description nextquestion returns something
description nextquestion returns something if called more than once
description Python implementation of nextquestion can be used
description Run post-survey analysis
description Answer questions, and obtain a sensible next question each time
description nextquestion returns something else
```

two scripts start with*test* instead of *description* statement

**Comment by gardners** [comment]
Please resolve the conflicts first.

**Comment by RoboSparrow** [comment]
@gardners , done. ready to merge.

**Comment by RoboSparrow** [comment]
actual, merging this myself

**Pull request merged**
